### PR TITLE
Fix sign convention in helmert macro

### LINKED ISSUE #307: Sign of rotation parameters in `@helmert` transform
@eliascarv I just noticed that the `@helmert` transform uses rotation angles with a different sign compared to the EPSG database. Is there a reason for that?

### PR DESCRIPTION
**Pull request by juliohm**
Fix #307

This simple change already helped find a bug with `OSGB36`.

### CODE REVIEW

**Comment by eliascarv** [comment]
The Coordinate Frame convention is not the only convention that can be found in the EPSG Dataset:
https://epsg.org/transformation_1314/OSGB36-to-WGS-84-6.html
So, we need to add a kwarg in the `@helmert` macro to support Position Vector parameters.

**Comment by juliohm** [comment]
In that case I think we can improve the docstring of the transform to be very explicit about these two options. I will update the PR to make this crystal clear.

**Comment by juliohm** [comment]
@eliascarv I've updated the parameters for the OSGB36 datum. The previous values in the source code had 4 decimal places, but the current link in the EPSG database only has 3 decimal places.

**Comment by juliohm** [comment]
Other than that, the PR is ready for review.

File: src/transforms/helmert.jl [hunk 1]
```diff
@@ -5,19 +5,37 @@
...
-### Notes
+https://epsg.org/transformation_1314/OSGB36-to-WGS-84-6.html
 
-The convention used for rotation is the Position Vector. 
-To set rotation parameters that use the Coordinate Frame
-convention, simply invert the sign of the parameters.
+The rotation parameters are given by `θx=-0.15`, `θy=-0.247` and `θz=-0.842`.
+
+It is worth noting that convention (1) is the most frequent convention in the
+EPSG database, and that convention (2) is the one adopted by the C PROJ library:
```
Comment (eliascarv) [inline src/transforms/helmert.jl:32]: PROJ supports both conventions, but I think this text implied that only the Position Vector convention is supported. Did I misunderstand?

**Comment by juliohm** [comment]
From what I understand in the datums.cpp it only supports one convention
when the angles are listed with a single sign, no?

Please feel free to suggest changes in the docstring.

Em sex., 20 de jun. de 2025, 09:43, Elias Carvalho ***@***.***>
escreveu:

**Review by eliascarv — APPROVED** [review]

**Comment by juliohm** [comment]
One final question before merging. The `timedephelmert` relies on `dt` to update the rotation parameters. Is `dt` mostly positive in the database? The formula is `theta' = theta + dtheta * dt`. Do we need to adjust `dt` accordingly now that both `theta` and `dtheta` flipped sign?

**Comment by juliohm** [comment]
I am assuming that because `theta` and `dtheta` have the same sign, everything will be fine when the parameters are sent to the underlying `helmert`.

Merging it.
